title: 继续向前 go rockets!
description:  # this means to ignore newlines until "baseurl:"
  2年 python 开发经验. 熟练使用Django,flask web框架, Django-Restful-Framework框架以及restful-api接口; 
  掌握MySQL，mongodb，redis等数据库操作;
  熟悉网络爬虫基本原理,Scrapy框架,scrapy-redis分布式爬虫,以及BeautifulSoup,xpath,css,Pyquery等数据提取方法;
  掌握HTML、CSS、JQuery等技术, 熟悉Python网络编程,以及多线程，多进程,协程等并行程序模型, 对分布式结构有一定了解;
  能够高效地沟通, 并与团队或跨团队同事有效地协作办公.
baseurl: "/melo108.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: 远山淡影
tagline: 全栈开发 python 爬虫爱好者
about-description:    
  2年 python 开发经验. 熟练使用Django,flask web框架, Django-Restful-Framework框架以及restful-api接口; 
  掌握MySQL，mongodb，redis等数据库操作;
  熟悉网络爬虫基本原理,Scrapy框架,scrapy-redis分布式爬虫,以及BeautifulSoup,xpath,css,Pyquery等数据提取方法;
  掌握HTML、CSS、JQuery等技术, 熟悉Python网络编程,以及多线程，多进程,协程等并行程序模型, 对分布式结构有一定了解;
  能够高效地沟通, 并与团队或跨团队同事有效地协作办公.
pic: rks.png  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: 542450010@qq.com # Add your Email address
website: https://www.cnblogs.com/big-handsome-guy # Add your website, do not add http://
github: melo108/melo108.github.io # Add your Github handle
weibo: jim10827297 # Add your Twitter handle https://weibo.com/jim10827297

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
